package datalayer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * AbstractCapability generated by hbm2java.
 * This class stores the capability informations, like the id and the name
 */
@Entity
@Table(name = "abstract_capability", catalog = "musa_db")
public class AbstractCapability implements java.io.Serializable {

	/** The id abstrat capability. */
	private int idAbstratCapability;
	
	/** The domain. */
	private Domain domain;
	
	/** The name. */
	private String name;
	
	/** The input. */
	private String input;
	
	/** The output. */
	private String output;
	
	/** The params. */
	private String params;
	
	/** The pre condition. */
	private String preCondition;
	
	/** The post condition. */
	private String postCondition;
	
	/** The concrete capabilities. */
	private Set<ConcreteCapability> concreteCapabilities = new HashSet<ConcreteCapability>(
			0);
	
	/** The scenario evos. */
	private Set<ScenarioEvo> scenarioEvos = new HashSet<ScenarioEvo>(0);

	/**
	 * Instantiates a new abstract capability.
	 */
	public AbstractCapability() {
	}

	/**
	 * Instantiates a new abstract capability.
	 *
	 * @param idAbstratCapability the id abstrat capability
	 */
	public AbstractCapability(int idAbstratCapability) {
		this.idAbstratCapability = idAbstratCapability;
	}

	/**
	 * Instantiates a new abstract capability.
	 *
	 * @param idAbstratCapability the id abstrat capability
	 * @param domain the domain
	 * @param name the name
	 * @param input the input
	 * @param output the output
	 * @param params the params
	 * @param preCondition the pre condition
	 * @param postCondition the post condition
	 * @param concreteCapabilities the concrete capabilities
	 * @param scenarioEvos the scenario evos
	 */
	public AbstractCapability(int idAbstratCapability, Domain domain,
			String name, String input, String output, String params,
			String preCondition, String postCondition,
			Set<ConcreteCapability> concreteCapabilities,
			Set<ScenarioEvo> scenarioEvos) {
		this.idAbstratCapability = idAbstratCapability;
		this.domain = domain;
		this.name = name;
		this.input = input;
		this.output = output;
		this.params = params;
		this.preCondition = preCondition;
		this.postCondition = postCondition;
		this.concreteCapabilities = concreteCapabilities;
		this.scenarioEvos = scenarioEvos;
	}

	/**
	 * Gets the id abstrat capability.
	 *
	 * @return the id abstrat capability
	 */
	@Id
	@Column(name = "idAbstrat_Capability", unique = true, nullable = false)
	public int getIdAbstratCapability() {
		return this.idAbstratCapability;
	}

	/**
	 * Sets the id abstrat capability.
	 *
	 * @param idAbstratCapability the new id abstrat capability
	 */
	public void setIdAbstratCapability(int idAbstratCapability) {
		this.idAbstratCapability = idAbstratCapability;
	}

	/**
	 * Gets the domain.
	 *
	 * @return the domain
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	/**
	 * Sets the domain.
	 *
	 * @param domain the new domain
	 */
	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the input.
	 *
	 * @return the input
	 */
	@Column(name = "input", length = 45)
	public String getInput() {
		return this.input;
	}

	/**
	 * Sets the input.
	 *
	 * @param input the new input
	 */
	public void setInput(String input) {
		this.input = input;
	}

	/**
	 * Gets the output.
	 *
	 * @return the output
	 */
	@Column(name = "output", length = 45)
	public String getOutput() {
		return this.output;
	}

	/**
	 * Sets the output.
	 *
	 * @param output the new output
	 */
	public void setOutput(String output) {
		this.output = output;
	}

	/**
	 * Gets the params.
	 *
	 * @return the params
	 */
	@Column(name = "params", length = 45)
	public String getParams() {
		return this.params;
	}

	/**
	 * Sets the params.
	 *
	 * @param params the new params
	 */
	public void setParams(String params) {
		this.params = params;
	}

	/**
	 * Gets the pre condition.
	 *
	 * @return the pre condition
	 */
	@Column(name = "pre-condition", length = 45)
	public String getPreCondition() {
		return this.preCondition;
	}

	/**
	 * Sets the pre condition.
	 *
	 * @param preCondition the new pre condition
	 */
	public void setPreCondition(String preCondition) {
		this.preCondition = preCondition;
	}

	/**
	 * Gets the post condition.
	 *
	 * @return the post condition
	 */
	@Column(name = "post_condition", length = 45)
	public String getPostCondition() {
		return this.postCondition;
	}

	/**
	 * Sets the post condition.
	 *
	 * @param postCondition the new post condition
	 */
	public void setPostCondition(String postCondition) {
		this.postCondition = postCondition;
	}

	/**
	 * Gets the concrete capabilities.
	 *
	 * @return the concrete capabilities
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abstractCapability")
	public Set<ConcreteCapability> getConcreteCapabilities() {
		return this.concreteCapabilities;
	}

	/**
	 * Sets the concrete capabilities.
	 *
	 * @param concreteCapabilities the new concrete capabilities
	 */
	public void setConcreteCapabilities(
			Set<ConcreteCapability> concreteCapabilities) {
		this.concreteCapabilities = concreteCapabilities;
	}

	/**
	 * Gets the scenario evos.
	 *
	 * @return the scenario evos
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abstractCapability")
	public Set<ScenarioEvo> getScenarioEvos() {
		return this.scenarioEvos;
	}

	/**
	 * Sets the scenario evos.
	 *
	 * @param scenarioEvos the new scenario evos
	 */
	public void setScenarioEvos(Set<ScenarioEvo> scenarioEvos) {
		this.scenarioEvos = scenarioEvos;
	}

}
