package org.icar.musa.persistence.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * DomainConfiguration generated by hbm2java.
 */
@Entity
@Table(name = "domain_configuration", catalog = "musa_db")
public class DomainConfiguration implements java.io.Serializable {

	/** The id domain configuration. */
	private int idDomainConfiguration;
	
	/** The domain. */
	private Domain domain;
	
	/** The name. */
	private String name;
	
	/** The value. */
	private String value;
	
	/** The description. */
	private String description;

	/**
	 * Instantiates a new domain configuration.
	 */
	public DomainConfiguration() {
	}

	/**
	 * Instantiates a new domain configuration.
	 *
	 * @param idDomainConfiguration the id domain configuration
	 */
	public DomainConfiguration(int idDomainConfiguration) {
		this.idDomainConfiguration = idDomainConfiguration;
	}

	/**
	 * Instantiates a new domain configuration.
	 *
	 * @param idDomainConfiguration the id domain configuration
	 * @param domain the domain
	 * @param name the name
	 * @param value the value
	 * @param description the description
	 */
	public DomainConfiguration(int idDomainConfiguration, Domain domain,
			String name, String value, String description) {
		this.idDomainConfiguration = idDomainConfiguration;
		this.domain = domain;
		this.name = name;
		this.value = value;
		this.description = description;
	}

	/**
	 * Gets the id domain configuration.
	 *
	 * @return the id domain configuration
	 */
	@Id
	@Column(name = "idDomain_Configuration", unique = true, nullable = false)
	public int getIdDomainConfiguration() {
		return this.idDomainConfiguration;
	}

	/**
	 * Sets the id domain configuration.
	 *
	 * @param idDomainConfiguration the new id domain configuration
	 */
	public void setIdDomainConfiguration(int idDomainConfiguration) {
		this.idDomainConfiguration = idDomainConfiguration;
	}

	/**
	 * Gets the domain.
	 *
	 * @return the domain
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	/**
	 * Sets the domain.
	 *
	 * @param domain the new domain
	 */
	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
