/* Generated By:JavaCC: Do not edit this line. JaCaMoProjectParserConstants.java */
package jacamo.project.parser;

public interface JaCaMoProjectParserConstants {

  int EOF = 0;
  int VAR = 5;
  int MAS = 6;
  int AGENT = 7;
  int INSTANCES = 8;
  int AGARCH = 9;
  int AGCLASS = 10;
  int AGBBCLASS = 11;
  int BELIEF = 12;
  int GOAL = 13;
  int NODE = 14;
  int FOCUS = 15;
  int JOIN = 16;
  int ROLES = 17;
  int IN = 18;
  int USES = 19;
  int CLASSPATH = 20;
  int ASLPATH = 21;
  int PLATFORM = 22;
  int DEBUG = 23;
  int RUNNING = 24;
  int WORKSPACE = 25;
  int ARTIFACT = 26;
  int FOCUSED = 27;
  int AGENTS = 28;
  int ORG = 29;
  int GROUP = 30;
  int RESPFOR = 31;
  int SCHEME = 32;
  int PLAYERS = 33;
  int TK_TRUE = 34;
  int TK_FALSE = 35;
  int TK_NOT = 36;
  int TK_NEG = 37;
  int TK_INTDIV = 38;
  int TK_INTMOD = 39;
  int TK_BEGIN = 40;
  int TK_END = 41;
  int EOL = 42;
  int IP = 43;
  int INT = 44;
  int REAL = 45;
  int STRING = 46;
  int AST = 47;
  int DOT = 48;
  int DOTDOT = 49;
  int ATOM = 50;
  int UNNAMEDVAR = 51;
  int CHAR = 52;
  int LETTER = 53;
  int LC_LETTER = 54;
  int UP_LETTER = 55;
  int DIGIT = 56;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<VAR>",
    "\"mas\"",
    "\"agent\"",
    "\"instances\"",
    "\"ag-arch\"",
    "\"ag-class\"",
    "\"ag-bb-class\"",
    "\"beliefs\"",
    "\"goals\"",
    "\"node\"",
    "\"focus\"",
    "\"join\"",
    "\"roles\"",
    "\"in\"",
    "\"uses\"",
    "\"class-path\"",
    "\"asl-path\"",
    "\"platform\"",
    "\"debug\"",
    "\"running\"",
    "\"workspace\"",
    "\"artifact\"",
    "\"focused-by\"",
    "\"agents\"",
    "\"organisation\"",
    "\"group\"",
    "\"responsible-for\"",
    "\"scheme\"",
    "\"players\"",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "\"div\"",
    "\"mod\"",
    "\"begin\"",
    "\"end\"",
    "<EOL>",
    "<IP>",
    "<INT>",
    "<REAL>",
    "<STRING>",
    "\"*\"",
    "\".\"",
    "<DOTDOT>",
    "<ATOM>",
    "<UNNAMEDVAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\",\"",
    "\"{\"",
    "\":\"",
    "\"@\"",
    "\"}\"",
    "\"/\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
