package org.icar.musa.utils.persistence.entity;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * FunctionalReq generated by hbm2java.
 */
@Entity
@Table(name = "functional_req", catalog = "musa_db")
public class FunctionalReq implements java.io.Serializable {

	/** The id functional req. */
	private Integer idFunctionalReq;
	
	/** The process. */
	private Process process;
	
	/** The specification. */
	private Specification specification;
	
	/** The name. */
	private String name;
	
	/** The type. */
	private String type;
	
	/** The description. */
	private String description;
	
	/** The current state. */
	private String currentState;
	
	/** The trigger condition. */
	private String triggerCondition;
	
	/** The final state. */
	private String finalState;

	/**
	 * Instantiates a new functional req.
	 */
	public FunctionalReq() {
	}

	/**
	 * Instantiates a new functional req.
	 *
	 * @param process the process
	 * @param specification the specification
	 * @param name the name
	 * @param type the type
	 * @param description the description
	 * @param currentState the current state
	 * @param triggerCondition the trigger condition
	 * @param finalState the final state
	 */
	public FunctionalReq(Process process, Specification specification,
			String name, String type, String description, String currentState,
			String triggerCondition, String finalState) {
		this.process = process;
		this.specification = specification;
		this.name = name;
		this.type = type;
		this.description = description;
		this.currentState = currentState;
		this.triggerCondition = triggerCondition;
		this.finalState = finalState;
	}

	/**
	 * Gets the id functional req.
	 *
	 * @return the id functional req
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFunctional_Req", unique = true, nullable = false)
	public Integer getIdFunctionalReq() {
		return this.idFunctionalReq;
	}

	/**
	 * Sets the id functional req.
	 *
	 * @param idFunctionalReq the new id functional req
	 */
	public void setIdFunctionalReq(Integer idFunctionalReq) {
		this.idFunctionalReq = idFunctionalReq;
	}

	/**
	 * Gets the process.
	 *
	 * @return the process
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idWF")
	public Process getProcess() {
		return this.process;
	}

	/**
	 * Sets the process.
	 *
	 * @param process the new process
	 */
	public void setProcess(Process process) {
		this.process = process;
	}

	/**
	 * Gets the specification.
	 *
	 * @return the specification
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idSpecification")
	public Specification getSpecification() {
		return this.specification;
	}

	/**
	 * Sets the specification.
	 *
	 * @param specification the new specification
	 */
	public void setSpecification(Specification specification) {
		this.specification = specification;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the current state.
	 *
	 * @return the current state
	 */
	@Column(name = "current_state", length = 45)
	public String getCurrentState() {
		return this.currentState;
	}

	/**
	 * Sets the current state.
	 *
	 * @param currentState the new current state
	 */
	public void setCurrentState(String currentState) {
		this.currentState = currentState;
	}

	/**
	 * Gets the trigger condition.
	 *
	 * @return the trigger condition
	 */
	@Column(name = "trigger_condition", length = 45)
	public String getTriggerCondition() {
		return this.triggerCondition;
	}

	/**
	 * Sets the trigger condition.
	 *
	 * @param triggerCondition the new trigger condition
	 */
	public void setTriggerCondition(String triggerCondition) {
		this.triggerCondition = triggerCondition;
	}

	/**
	 * Gets the final state.
	 *
	 * @return the final state
	 */
	@Column(name = "final_state", length = 45)
	public String getFinalState() {
		return this.finalState;
	}

	/**
	 * Sets the final state.
	 *
	 * @param finalState the new final state
	 */
	public void setFinalState(String finalState) {
		this.finalState = finalState;
	}

}
