package org.icar.musa.utils.persistence.entity;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * GeneralConfiguration generated by hbm2java.
 */
@Entity
@Table(name = "general_configuration", catalog = "musa_db")
public class GeneralConfiguration implements java.io.Serializable {

	/** The id general configuration. */
	private Integer idGeneralConfiguration;
	
	/** The name. */
	private String name;
	
	/** The value. */
	private String value;
	
	/** The description. */
	private String description;

	/**
	 * Instantiates a new general configuration.
	 */
	public GeneralConfiguration() {
	}

	/**
	 * Instantiates a new general configuration.
	 *
	 * @param name the name
	 * @param value the value
	 * @param description the description
	 */
	public GeneralConfiguration(String name, String value, String description) {
		this.name = name;
		this.value = value;
		this.description = description;
	}

	/**
	 * Gets the id general configuration.
	 *
	 * @return the id general configuration
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGeneral_Configuration", unique = true, nullable = false)
	public Integer getIdGeneralConfiguration() {
		return this.idGeneralConfiguration;
	}

	/**
	 * Sets the id general configuration.
	 *
	 * @param idGeneralConfiguration the new id general configuration
	 */
	public void setIdGeneralConfiguration(Integer idGeneralConfiguration) {
		this.idGeneralConfiguration = idGeneralConfiguration;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the value.
	 *
	 * @return the value
	 */
	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	/**
	 * Sets the value.
	 *
	 * @param value the new value
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
