package org.icar.musa.utils.persistence.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Predicate generated by hbm2java.
 */
@Entity
@Table(name = "predicate", catalog = "musa_db")
public class Predicate implements java.io.Serializable {

	/** The id predicate. */
	private int idPredicate;
	
	/** The name. */
	private String name;
	
	/** The description. */
	private String description;
	
	/** The id case. */
	private Integer idCase;

	/**
	 * Instantiates a new predicate.
	 */
	public Predicate() {
	}

	/**
	 * Instantiates a new predicate.
	 *
	 * @param idPredicate the id predicate
	 */
	public Predicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	/**
	 * Instantiates a new predicate.
	 *
	 * @param idPredicate the id predicate
	 * @param name the name
	 * @param description the description
	 * @param idCase the id case
	 */
	public Predicate(int idPredicate, String name, String description,
			Integer idCase) {
		this.idPredicate = idPredicate;
		this.name = name;
		this.description = description;
		this.idCase = idCase;
	}

	/**
	 * Gets the id predicate.
	 *
	 * @return the id predicate
	 */
	@Id
	@Column(name = "idPredicate", unique = true, nullable = false)
	public int getIdPredicate() {
		return this.idPredicate;
	}

	/**
	 * Sets the id predicate.
	 *
	 * @param idPredicate the new id predicate
	 */
	public void setIdPredicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * Gets the id case.
	 *
	 * @return the id case
	 */
	@Column(name = "idCase")
	public Integer getIdCase() {
		return this.idCase;
	}

	/**
	 * Sets the id case.
	 *
	 * @param idCase the new id case
	 */
	public void setIdCase(Integer idCase) {
		this.idCase = idCase;
	}

}
