package datalayer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * ConcreteCapability generated by hbm2java.
 */
@Entity
@Table(name = "concrete_capability", catalog = "musa_db")
public class ConcreteCapability implements java.io.Serializable {

	/** The id concrete capability. */
	private Integer idConcreteCapability;
	
	/** The abstract capability. */
	private AbstractCapability abstractCapability;
	
	/** The file upload. */
	private byte[] fileUpload;
	
	/** The provider. */
	private String provider;
	
	/** The id. */
	private String id;
	
	/** The capability instances. */
	private Set<CapabilityInstance> capabilityInstances = new HashSet<CapabilityInstance>(
			0);

	/**
	 * Instantiates a new concrete capability.
	 */
	public ConcreteCapability() {
	}

	/**
	 * Instantiates a new concrete capability.
	 *
	 * @param abstractCapability the abstract capability
	 * @param fileUpload the file upload
	 * @param provider the provider
	 * @param id the id
	 * @param capabilityInstances the capability instances
	 */
	public ConcreteCapability(AbstractCapability abstractCapability,
			byte[] fileUpload, String provider, String id,
			Set<CapabilityInstance> capabilityInstances) {
		this.abstractCapability = abstractCapability;
		this.fileUpload = fileUpload;
		this.provider = provider;
		this.id = id;
		this.capabilityInstances = capabilityInstances;
	}

	/**
	 * Gets the id concrete capability.
	 *
	 * @return the id concrete capability
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idConcrete_Capability", unique = true, nullable = false)
	public Integer getIdConcreteCapability() {
		return this.idConcreteCapability;
	}

	/**
	 * Sets the id concrete capability.
	 *
	 * @param idConcreteCapability the new id concrete capability
	 */
	public void setIdConcreteCapability(Integer idConcreteCapability) {
		this.idConcreteCapability = idConcreteCapability;
	}

	/**
	 * Gets the abstract capability.
	 *
	 * @return the abstract capability
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAbstract_Capability")
	public AbstractCapability getAbstractCapability() {
		return this.abstractCapability;
	}

	/**
	 * Sets the abstract capability.
	 *
	 * @param abstractCapability the new abstract capability
	 */
	public void setAbstractCapability(AbstractCapability abstractCapability) {
		this.abstractCapability = abstractCapability;
	}

	/**
	 * Gets the file upload.
	 *
	 * @return the file upload
	 */
	@Column(name = "fileUpload")
	public byte[] getFileUpload() {
		return this.fileUpload;
	}

	/**
	 * Sets the file upload.
	 *
	 * @param fileUpload the new file upload
	 */
	public void setFileUpload(byte[] fileUpload) {
		this.fileUpload = fileUpload;
	}

	/**
	 * Gets the provider.
	 *
	 * @return the provider
	 */
	@Column(name = "Provider", length = 45)
	public String getProvider() {
		return this.provider;
	}

	/**
	 * Sets the provider.
	 *
	 * @param provider the new provider
	 */
	public void setProvider(String provider) {
		this.provider = provider;
	}

	/**
	 * Gets the id.
	 *
	 * @return the id
	 */
	@Column(name = "id", length = 45)
	public String getId() {
		return this.id;
	}

	/**
	 * Sets the id.
	 *
	 * @param id the new id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Gets the capability instances.
	 *
	 * @return the capability instances
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "concreteCapability")
	public Set<CapabilityInstance> getCapabilityInstances() {
		return this.capabilityInstances;
	}

	/**
	 * Sets the capability instances.
	 *
	 * @param capabilityInstances the new capability instances
	 */
	public void setCapabilityInstances(
			Set<CapabilityInstance> capabilityInstances) {
		this.capabilityInstances = capabilityInstances;
	}

}
