package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AbstractCapability generated by hbm2java
 */
@Entity
@Table(name = "abstract_capability", catalog = "musa_db")
public class AbstractCapability implements java.io.Serializable {

	private int idAbstratCapability;
	private Domain domain;
	private String name;
	private String input;
	private String output;
	private String params;
	private String preCondition;
	private String postCondition;
	private Set<ConcreteCapability> concreteCapabilities = new HashSet<ConcreteCapability>(
			0);
	private Set<ScenarioEvo> scenarioEvos = new HashSet<ScenarioEvo>(0);

	public AbstractCapability() {
	}

	public AbstractCapability(int idAbstratCapability) {
		this.idAbstratCapability = idAbstratCapability;
	}

	public AbstractCapability(int idAbstratCapability, Domain domain,
			String name, String input, String output, String params,
			String preCondition, String postCondition,
			Set<ConcreteCapability> concreteCapabilities,
			Set<ScenarioEvo> scenarioEvos) {
		this.idAbstratCapability = idAbstratCapability;
		this.domain = domain;
		this.name = name;
		this.input = input;
		this.output = output;
		this.params = params;
		this.preCondition = preCondition;
		this.postCondition = postCondition;
		this.concreteCapabilities = concreteCapabilities;
		this.scenarioEvos = scenarioEvos;
	}

	@Id
	@Column(name = "idAbstrat_Capability", unique = true, nullable = false)
	public int getIdAbstratCapability() {
		return this.idAbstratCapability;
	}

	public void setIdAbstratCapability(int idAbstratCapability) {
		this.idAbstratCapability = idAbstratCapability;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "input", length = 45)
	public String getInput() {
		return this.input;
	}

	public void setInput(String input) {
		this.input = input;
	}

	@Column(name = "output", length = 45)
	public String getOutput() {
		return this.output;
	}

	public void setOutput(String output) {
		this.output = output;
	}

	@Column(name = "params", length = 45)
	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	@Column(name = "pre-condition", length = 45)
	public String getPreCondition() {
		return this.preCondition;
	}

	public void setPreCondition(String preCondition) {
		this.preCondition = preCondition;
	}

	@Column(name = "post_condition", length = 45)
	public String getPostCondition() {
		return this.postCondition;
	}

	public void setPostCondition(String postCondition) {
		this.postCondition = postCondition;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abstractCapability")
	public Set<ConcreteCapability> getConcreteCapabilities() {
		return this.concreteCapabilities;
	}

	public void setConcreteCapabilities(
			Set<ConcreteCapability> concreteCapabilities) {
		this.concreteCapabilities = concreteCapabilities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "abstractCapability")
	public Set<ScenarioEvo> getScenarioEvos() {
		return this.scenarioEvos;
	}

	public void setScenarioEvos(Set<ScenarioEvo> scenarioEvos) {
		this.scenarioEvos = scenarioEvos;
	}

}
