package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CapabilityInstance generated by hbm2java
 */
@Entity
@Table(name = "capability_instance", catalog = "musa_db")
public class CapabilityInstance implements java.io.Serializable {

	private Integer idCapabilityInstance;
	private ConcreteCapability concreteCapability;
	private String state;
	private String agent;
	private Integer idCase;
	private Set<CapabilityLog> capabilityLogs = new HashSet<CapabilityLog>(0);

	public CapabilityInstance() {
	}

	public CapabilityInstance(ConcreteCapability concreteCapability,
			String state, String agent, Integer idCase,
			Set<CapabilityLog> capabilityLogs) {
		this.concreteCapability = concreteCapability;
		this.state = state;
		this.agent = agent;
		this.idCase = idCase;
		this.capabilityLogs = capabilityLogs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCapability_Instance", unique = true, nullable = false)
	public Integer getIdCapabilityInstance() {
		return this.idCapabilityInstance;
	}

	public void setIdCapabilityInstance(Integer idCapabilityInstance) {
		this.idCapabilityInstance = idCapabilityInstance;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCapability")
	public ConcreteCapability getConcreteCapability() {
		return this.concreteCapability;
	}

	public void setConcreteCapability(ConcreteCapability concreteCapability) {
		this.concreteCapability = concreteCapability;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "agent", length = 45)
	public String getAgent() {
		return this.agent;
	}

	public void setAgent(String agent) {
		this.agent = agent;
	}

	@Column(name = "idCase")
	public Integer getIdCase() {
		return this.idCase;
	}

	public void setIdCase(Integer idCase) {
		this.idCase = idCase;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capabilityInstance")
	public Set<CapabilityLog> getCapabilityLogs() {
		return this.capabilityLogs;
	}

	public void setCapabilityLogs(Set<CapabilityLog> capabilityLogs) {
		this.capabilityLogs = capabilityLogs;
	}

}
