package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * CapabilityLog generated by hbm2java.
 */
@Entity
@Table(name = "capability_log", catalog = "musa_db")
public class CapabilityLog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id capability operation. */
	private Integer idCapabilityOperation;

	/** The capability instance. */
	private CapabilityInstance capabilityInstance;

	/** The time operation. */
	private String timeOperation;

	/** The action. */
	private String action;

	/**
	 * Instantiates a new capability log.
	 */
	public CapabilityLog() {
	}

	/**
	 * Instantiates a new capability log.
	 *
	 * @param capabilityInstance the capability instance
	 * @param timeOperation the time operation
	 * @param action the action
	 */
	public CapabilityLog(CapabilityInstance capabilityInstance,
			String timeOperation, String action) {
		this.capabilityInstance = capabilityInstance;
		this.timeOperation = timeOperation;
		this.action = action;
	}

	/**
	 * Gets the id capability operation.
	 *
	 * @return the id capability operation
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCapability_Operation", unique = true, nullable = false)
	public Integer getIdCapabilityOperation() {
		return this.idCapabilityOperation;
	}

	/**
	 * Sets the id capability operation.
	 *
	 * @param idCapabilityOperation the new id capability operation
	 */
	public void setIdCapabilityOperation(Integer idCapabilityOperation) {
		this.idCapabilityOperation = idCapabilityOperation;
	}

	/**
	 * Gets the capability instance.
	 *
	 * @return the capability instance
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInstance")
	public CapabilityInstance getCapabilityInstance() {
		return this.capabilityInstance;
	}

	/**
	 * Sets the capability instance.
	 *
	 * @param capabilityInstance the new capability instance
	 */
	public void setCapabilityInstance(CapabilityInstance capabilityInstance) {
		this.capabilityInstance = capabilityInstance;
	}

	/**
	 * Gets the time operation.
	 *
	 * @return the time operation
	 */
	@Column(name = "timeOperation", length = 45)
	public String getTimeOperation() {
		return this.timeOperation;
	}

	/**
	 * Sets the time operation.
	 *
	 * @param timeOperation the new time operation
	 */
	public void setTimeOperation(String timeOperation) {
		this.timeOperation = timeOperation;
	}

	/**
	 * Gets the action.
	 *
	 * @return the action
	 */
	@Column(name = "action", length = 45)
	public String getAction() {
		return this.action;
	}

	/**
	 * Sets the action.
	 *
	 * @param action the new action
	 */
	public void setAction(String action) {
		this.action = action;
	}

}
