package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CapabilityLog generated by hbm2java
 */
@Entity
@Table(name = "capability_log", catalog = "musa_db")
public class CapabilityLog implements java.io.Serializable {

	private Integer idCapabilityOperation;
	private CapabilityInstance capabilityInstance;
	private String timeOperation;
	private String action;

	public CapabilityLog() {
	}

	public CapabilityLog(CapabilityInstance capabilityInstance,
			String timeOperation, String action) {
		this.capabilityInstance = capabilityInstance;
		this.timeOperation = timeOperation;
		this.action = action;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCapability_Operation", unique = true, nullable = false)
	public Integer getIdCapabilityOperation() {
		return this.idCapabilityOperation;
	}

	public void setIdCapabilityOperation(Integer idCapabilityOperation) {
		this.idCapabilityOperation = idCapabilityOperation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idInstance")
	public CapabilityInstance getCapabilityInstance() {
		return this.capabilityInstance;
	}

	public void setCapabilityInstance(CapabilityInstance capabilityInstance) {
		this.capabilityInstance = capabilityInstance;
	}

	@Column(name = "timeOperation", length = 45)
	public String getTimeOperation() {
		return this.timeOperation;
	}

	public void setTimeOperation(String timeOperation) {
		this.timeOperation = timeOperation;
	}

	@Column(name = "action", length = 45)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
