package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DomainConfiguration generated by hbm2java
 */
@Entity
@Table(name = "domain_configuration", catalog = "musa_db")
public class DomainConfiguration implements java.io.Serializable {

	private int idDomainConfiguration;
	private Domain domain;
	private String name;
	private String value;
	private String description;

	public DomainConfiguration() {
	}

	public DomainConfiguration(int idDomainConfiguration) {
		this.idDomainConfiguration = idDomainConfiguration;
	}

	public DomainConfiguration(int idDomainConfiguration, Domain domain,
			String name, String value, String description) {
		this.idDomainConfiguration = idDomainConfiguration;
		this.domain = domain;
		this.name = name;
		this.value = value;
		this.description = description;
	}

	@Id
	@Column(name = "idDomain_Configuration", unique = true, nullable = false)
	public int getIdDomainConfiguration() {
		return this.idDomainConfiguration;
	}

	public void setIdDomainConfiguration(int idDomainConfiguration) {
		this.idDomainConfiguration = idDomainConfiguration;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
