package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GeneralConfiguration generated by hbm2java
 */
@Entity
@Table(name = "general_configuration", catalog = "musa_db")
public class GeneralConfiguration implements java.io.Serializable {

	private Integer idGeneralConfiguration;
	private String name;
	private String value;
	private String description;

	public GeneralConfiguration() {
	}

	public GeneralConfiguration(String name, String value, String description) {
		this.name = name;
		this.value = value;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idGeneral_Configuration", unique = true, nullable = false)
	public Integer getIdGeneralConfiguration() {
		return this.idGeneralConfiguration;
	}

	public void setIdGeneralConfiguration(Integer idGeneralConfiguration) {
		this.idGeneralConfiguration = idGeneralConfiguration;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
