package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Predicate generated by hbm2java
 */
@Entity
@Table(name = "predicate", catalog = "musa_db")
public class Predicate implements java.io.Serializable {

	private int idPredicate;
	private String name;
	private String description;
	private Integer idCase;

	public Predicate() {
	}

	public Predicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	public Predicate(int idPredicate, String name, String description,
			Integer idCase) {
		this.idPredicate = idPredicate;
		this.name = name;
		this.description = description;
		this.idCase = idCase;
	}

	@Id
	@Column(name = "idPredicate", unique = true, nullable = false)
	public int getIdPredicate() {
		return this.idPredicate;
	}

	public void setIdPredicate(int idPredicate) {
		this.idPredicate = idPredicate;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "idCase")
	public Integer getIdCase() {
		return this.idCase;
	}

	public void setIdCase(Integer idCase) {
		this.idCase = idCase;
	}

}
