package layer.database.entity;

import static javax.persistence.GenerationType.IDENTITY;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * ScenarioEvo generated by hbm2java.
 */
@Entity
@Table(name = "scenario_evo", catalog = "musa_db")
public class ScenarioEvo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	/** The id scenario evo. */
	private Integer idScenarioEvo;

	/** The abstract capability. */
	private AbstractCapability abstractCapability;

	/** The type. */
	private String type;

	/** The description. */
	private String description;

	/**
	 * Instantiates a new scenario evo.
	 */
	public ScenarioEvo() {
	}

	/**
	 * Instantiates a new scenario evo.
	 *
	 * @param abstractCapability
	 *            the abstract capability
	 * @param type
	 *            the type
	 * @param description
	 *            the description
	 */
	public ScenarioEvo(AbstractCapability abstractCapability, String type, String description) {
		this.abstractCapability = abstractCapability;
		this.type = type;
		this.description = description;
	}

	/**
	 * Gets the id scenario evo.
	 *
	 * @return the id scenario evo
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idScenario_Evo", unique = true, nullable = false)
	public Integer getIdScenarioEvo() {
		return this.idScenarioEvo;
	}

	/**
	 * Sets the id scenario evo.
	 *
	 * @param idScenarioEvo
	 *            the new id scenario evo
	 */
	public void setIdScenarioEvo(Integer idScenarioEvo) {
		this.idScenarioEvo = idScenarioEvo;
	}

	/**
	 * Gets the abstract capability.
	 *
	 * @return the abstract capability
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAbstract_Cap")
	public AbstractCapability getAbstractCapability() {
		return this.abstractCapability;
	}

	/**
	 * Sets the abstract capability.
	 *
	 * @param abstractCapability
	 *            the new abstract capability
	 */
	public void setAbstractCapability(AbstractCapability abstractCapability) {
		this.abstractCapability = abstractCapability;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type
	 *            the new type
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * Gets the description.
	 *
	 * @return the description
	 */
	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	/**
	 * Sets the description.
	 *
	 * @param description
	 *            the new description
	 */
	public void setDescription(String description) {
		this.description = description;
	}

}
