package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ScenarioEvo generated by hbm2java
 */
@Entity
@Table(name = "scenario_evo", catalog = "musa_db")
public class ScenarioEvo implements java.io.Serializable {

	private Integer idScenarioEvo;
	private AbstractCapability abstractCapability;
	private String type;
	private String description;

	public ScenarioEvo() {
	}

	public ScenarioEvo(AbstractCapability abstractCapability, String type,
			String description) {
		this.abstractCapability = abstractCapability;
		this.type = type;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idScenario_Evo", unique = true, nullable = false)
	public Integer getIdScenarioEvo() {
		return this.idScenarioEvo;
	}

	public void setIdScenarioEvo(Integer idScenarioEvo) {
		this.idScenarioEvo = idScenarioEvo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idAbstract_Cap")
	public AbstractCapability getAbstractCapability() {
		return this.abstractCapability;
	}

	public void setAbstractCapability(AbstractCapability abstractCapability) {
		this.abstractCapability = abstractCapability;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
