package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Specification generated by hbm2java
 */
@Entity
@Table(name = "specification", catalog = "musa_db")
public class Specification implements java.io.Serializable {

	private Integer idSpecification;
	private Domain domain;
	private String descriptions;
	private String state;
	private String user;
	private Set<FunctionalReq> functionalReqs = new HashSet<FunctionalReq>(0);
	private Set<NonFunctionalReq> nonFunctionalReqs = new HashSet<NonFunctionalReq>(
			0);

	public Specification() {
	}

	public Specification(Domain domain, String descriptions, String state,
			String user, Set<FunctionalReq> functionalReqs,
			Set<NonFunctionalReq> nonFunctionalReqs) {
		this.domain = domain;
		this.descriptions = descriptions;
		this.state = state;
		this.user = user;
		this.functionalReqs = functionalReqs;
		this.nonFunctionalReqs = nonFunctionalReqs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSpecification", unique = true, nullable = false)
	public Integer getIdSpecification() {
		return this.idSpecification;
	}

	public void setIdSpecification(Integer idSpecification) {
		this.idSpecification = idSpecification;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idDomain")
	public Domain getDomain() {
		return this.domain;
	}

	public void setDomain(Domain domain) {
		this.domain = domain;
	}

	@Column(name = "descriptions", length = 45)
	public String getDescriptions() {
		return this.descriptions;
	}

	public void setDescriptions(String descriptions) {
		this.descriptions = descriptions;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "user", length = 45)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<FunctionalReq> getFunctionalReqs() {
		return this.functionalReqs;
	}

	public void setFunctionalReqs(Set<FunctionalReq> functionalReqs) {
		this.functionalReqs = functionalReqs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "specification")
	public Set<NonFunctionalReq> getNonFunctionalReqs() {
		return this.nonFunctionalReqs;
	}

	public void setNonFunctionalReqs(Set<NonFunctionalReq> nonFunctionalReqs) {
		this.nonFunctionalReqs = nonFunctionalReqs;
	}

}
