package layer.database.entity;

// Generated 22-nov-2016 14.40.56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable", catalog = "musa_db")
public class Variable implements java.io.Serializable {

	private Integer idVariable;
	private String name;
	private String value;
	private Integer idCase;

	public Variable() {
	}

	public Variable(String name, String value, Integer idCase) {
		this.name = name;
		this.value = value;
		this.idCase = idCase;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVariable", unique = true, nullable = false)
	public Integer getIdVariable() {
		return this.idVariable;
	}

	public void setIdVariable(Integer idVariable) {
		this.idVariable = idVariable;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "idCase")
	public Integer getIdCase() {
		return this.idCase;
	}

	public void setIdCase(Integer idCase) {
		this.idCase = idCase;
	}

}
