package pmr.probexp;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;

import layer.awareness.AbstractCapability;
import layer.awareness.DomainEntail;
import layer.awareness.LTL.formulamodel.FormulaBT;
import layer.awareness.LTL.net.*;
import layer.semantic.AssumptionSet;
import layer.semantic.StateOfWorld;
import layer.semantic.WorldEvolution;
import layer.semantic.evolution.EvolutionScenario;
import petrinet.logic.Arc;
import petrinet.logic.Transition;
import pmr.graph.WorldNode;
 
/**
 * The Artifact ProblemExploration. It's used by an Agent to perform evolution for the various StateOfWorld passed, using his Capability.
 * It keeps a list of all the expanded nodes ready for bidding in auctions.
 * @author Alessandro Fontana
 * @author Mirko Zichichi
 */
public class ProblemExploration {

	/** The Assumption Set defined globally that the Agent has to maintain */
	private AssumptionSet assumptions;
	
	/** The Capabilities List that an Agent holds */
	private ArrayList<AbstractCapability> capabilities;
	
	/** The sorted List of ENode to visit */
	private ArrayList<ENode> toVisit;
	
	/** The List of visited ENode */
	private Set<StateOfWorld> visited;
	
	/** The sorted List that contains all the ExpansionNodes generated by the Agent  */
	private ArrayList<ExpansionNode> expandedList;
	
	/** Nets generated from the LTL Formula*/
	private Nets nets;
	
	/**
	 * Instantiates a new ProblemExploration.
	 *
	 * @param model
	 *            the Formula Model to follow
	 * @param capabilities
	 *            the Capabilities List proper of the Agent
	 * @param assumptions
	 *            the assumptions
	 */
	public ProblemExploration( FormulaBT model, ArrayList<AbstractCapability> capabilities, AssumptionSet assumptions) {
		this.capabilities = new ArrayList<>(capabilities);
		this.assumptions = assumptions;
		toVisit = new ArrayList<>();
		visited = new HashSet<>();
		expandedList = new ArrayList<>();
		nets = new Nets(model);
	}

	/**
	 * This Operation is used to add a new world node to the toVisit List.
	 *
	 * @param node
	 *            the WorldNode from SolutionGraph
	 * @param tokens
	 *            the Tokens List associated to that node 
	 * @param score
	 *            the Score associated to that node
	 */
	public void addToVisit( WorldNode node, TokensConfiguration tokens, int score) {
		if( !visited.contains(node.getWorldState()) && !toVisit.contains(new ENode(node.getWorldState())))
			toVisit.add( new ENode(node.getWorldState(), tokens, score, false) );
	}
	
	/**
	 * The main operation, it's used to expand an ENode from the toVisit List.
	 * It entails if one of is Capability is compatible with the StateOfWorld contained in the ENode.
	 * If so, it calls a set of methods used to ultimate the expansion, in order: applyExpand, applyNet, score.
	 * Finally, whatever the case is, it adds the ENode to the visited List. 
	 */
	public void expandNode() {
		
		ENode enode = getHighestNodeToVisit();

		if(enode == null)	return;
		
		visited.add(enode.getWorldState());
		
		for( int i = 0; i < capabilities.size(); i++ ){
			AbstractCapability capability = capabilities.get(i);
			if(DomainEntail.getInstance().entailsCondition(enode.getWorldState(), this.assumptions, capability.getPreCondition()) == true){
				//Starts the expansion

				ExpansionNode expNode = applyExpand(enode, capability);

				if (expNode != null){
					//Applies the net to ultimate the expansion						
					for( ENode destination : expNode.getDestination() ){
						applyNets(expNode.getSource().getTokens(), destination);
						if(destination.isExitNode() == false)	this.addToVisit(new WorldNode(destination.getWorldState()), destination.getTokens(), destination.getScore());
					}
				
					//Elaborates the Expansion score				
					score(expNode);
									
					//Adds the Expansion to the List in order 
					expandedList.add(expNode);
				}
			}
		}
	}	
	
	/**
	 * Operation used to get the highest ExpansionNode
	 *
	 * @return the highest ExpansionNode
	 */
	public ExpansionNode getHighestExpansion(){
		
		if(this.expandedList.size() == 0)	return null;
		
		expandedList.sort(ExpansionNode.getScoreComparator());
		int index = this.expandedList.size() - 1;
		return this.expandedList.get(index);
	}
	
	public void removeExpandedNode(ExpansionNode node){
		if(node == null)	return;
		this.expandedList.remove(node);
//		if(this.expandedList.remove(node))
//			System.out.println("HO RIMOSSO IL NODO.");
	}
	
	/**
	 * Method that creates the expanded States of World from the ENode, applying the evolution scenario from the capability
	 *
	 * @param enode
	 *            the ENode
	 * @param capability
	 *            the capability
	 * @return the expansion node
	 */
	private ExpansionNode applyExpand( ENode enode, AbstractCapability capability) {
		//Simple evolution, managed by NormalExpansionNode
		if(capability.getScenarioSet().size() == 1){
			//WorldEvolution is given by the AssumptionSet and the StateOfWorld
			WorldEvolution evo = new WorldEvolution(this.assumptions, enode.getWorldState());
			
			//Without iterator I can't access to the elements in ScenarioSet. It's just one element, the last one in the list
			//of evolutions. Anyway WorldEvolution saves the StateOfWorld source.
			Iterator<EvolutionScenario> i = capability.getScenarioSet().iterator();
			if(i.hasNext()){
				EvolutionScenario temp =(EvolutionScenario) i.next();
				evo.addEvolution(temp.getOperators());
			}
		
			ArrayList<ENode> newEnodeList = new ArrayList<ENode>();
			if(evo.getEvolution().getLast().equals(enode.getWorldState()) == false){
				ENode newEnode = new ENode(evo.getEvolution().getLast());
				newEnodeList.add(newEnode);
				//String scenario = (String)capability.getScenarioSet().iterator().next().getName();
				ExpansionNode result = new NormalExpansionNode(enode, newEnodeList, capability.getId());
				return result;
			}
			else	return null;
		}
		else{
			//When Capability's got more than one Scenario, I have to create a WorldEvolution for each Scenario. Every WorldEvolution 
			//will produce a StateOfWorld, that would be stored in a Node (that would get to the destinations list in MultipleExpansioNode. 
			//It will also update the Node-Scenario map with the Node-Scenario entry.
			MultipleExpansionNode expNode = new MultipleExpansionNode(enode, new ArrayList<ENode>(), capability.getId());
			
			Iterator<EvolutionScenario> i = capability.getScenarioSet().iterator();
			while(i.hasNext()){
				WorldEvolution evo = new WorldEvolution(this.assumptions, enode.getWorldState());
				EvolutionScenario temp = (EvolutionScenario) i.next();
				evo.addEvolution(temp.getOperators());
				if(evo.getEvolution().getLast().equals(enode.getWorldState()) == false){
					ENode newEnode = new ENode(evo.getEvolution().getLast());
					expNode.addDestination(newEnode);
					expNode.addScenario(newEnode, temp.getName());
				}
			}
			ExpansionNode result = expNode;
			return result;
		}
	}
	
	/**
	 * After the expansion a new ENode has been created, but it's empty. This
	 * method fills up the remaining attributes using the Net.
	 * 
	 * For every transition able to fire, it checks if the new state of world
	 * entails the condition labeled in the transition (trigger condition or
	 * final state). Then if the condition is true, it fires the token and
	 * elaborate the new token map. Finally it calls fillENode to fill up the
	 * ENode.
	 * 
	 * It handles the creation of a new Token List considering the OR "special"
	 * condition. Every Conditional Case has an InitialOrPlace and a FinalOrPlace.
	 * The InitialOrPlace has a special MultipleToken that allows to start 
	 * multiple parallel path for that case. In every path, called Branch, every
	 * new Token is created dependent from the MultipleToken and with his branch
	 * stored. When the first Token gets to the FinalOrPlace, it wins the "race"
	 * and all the remaining Tokens in every parallel path are destroyed.
	 *
	 * This method is used in applyNet to fill up the remaining attributes in ENode.
	 * 
	 * First part consists in setting the list of tokens.
	 * 
	 * Second part consists in calculating the Hops in the net and checking if it's an exit node.
	 * 
	 * In third part the SCORE is elaborated using a function that follows a color rule.
	 * The function sets a promising node at a value near 255 to represent WHITE, 0 for BLACK,  or
	 * in between to represent GRAY.
	 *
	 * @param startingTokens
	 *            the list of token to start with
	 * @param enode
	 *            the new eNode created from expansion
	 */
	
	private void applyNets( TokensConfiguration startingTokens, ENode enode ) {
		StateOfWorld state = enode.getWorldState();
		TokensConfiguration tokens = new TokensConfiguration(startingTokens);
		
		HashSet<String> visitedNets = new HashSet<>();
		
		//Prepares the net with tokens
		nets.putTokens(tokens);
		
		//Checking compatibility with StateOfWorld through every net, starting from first
		scanNet(tokens, nets.getStartingNet(), state, visitedNets);
		
		//Fills up ENode
		enode.setTokens(tokens);
		
		//Checking if it's an exit node
		enode.setExit( nets.getStartingPN().getNetState().equals("A") );
		
		//Calculating Hops
		int nHop = nets.hop(); 
		
		//Elaborating score
		int score = 0;
		if( enode.isExitNode() ) 
			score = 255;
		else 
			score = nHop; //(int) 255 - (255 / net.getNumTransitions()) * nHop;
		enode.setScore(score);
		
		//Cleans the net from tokens
		nets.removeTokens();
	}
	
	private void scanNet( TokensConfiguration tokens, String net, StateOfWorld state, HashSet<String> visitedNets ) {
		visitedNets.add(net);
		//Checking compatibility with StateOfWorld for every Transition for Firing
		for( Transition t : (ArrayList<Transition>) nets.getTransitionsAbleToFire(net) ){
			if( t.canFire() ){
				//Take a different path if the transition has a condition containing a Formula, a Proposition or a Composed Formula 
				TransitionCondition tCond = nets.getTransitionCondition(t);
				//Formula
				if( tCond instanceof FormulaCondition )
					if( formulaCheck(tCond, tokens, state, visitedNets) )
						fire(t, tokens, net);	//Fires if the condition matches with the state
				//Proposition
				else if( tCond instanceof SimpleCondition )
					if( DomainEntail.getInstance().entailsCondition(state, assumptions, ((SimpleCondition) tCond).getCondition()) )
						fire(t, tokens, net);
				//Composition
				else{
					Boolean[] tmpArr = new Boolean[2];
					int count = 0;
					for( TransitionCondition tCCond : ((CombinationCondition) tCond).getCond() )
						//Formula
						if( tCCond instanceof FormulaCondition )
							if( formulaCheck(tCCond, tokens, state, visitedNets) )
								tmpArr[count++] = true;	//Fires if the condition matches with the state
						//Proposition
						else if( tCCond instanceof SimpleCondition )
							if( DomainEntail.getInstance().entailsCondition(state, assumptions, ((SimpleCondition) tCCond).getCondition()) )
								tmpArr[count++] = true;
					if( tmpArr[0] && tmpArr[1] )
						fire(t, tokens, net);
				}
			}
		}
	}
	
	private Boolean formulaCheck(TransitionCondition tCond, TokensConfiguration tokens, StateOfWorld state, HashSet<String> visitedNets) {
		String cNet = tCond.getTerm(), cNetState = tokens.getNetState(cNet);
		//In this case the net representing the formula hasn't been accessed yet 
		if( cNetState == null ){ 
			tokens.addToken(cNet, nets.initNet(cNet)); //So initialize
			tokens.setNetState(cNet, "W");
			cNetState = "W";
		}
		//Checks if the formula condition became Accepted or Error
		if( cNetState.equals("W") && !visited.contains(cNetState) )
			scanNet( tokens, cNet, state, visitedNets );
		
		return tokens.getNetState(cNet).equals( ((FormulaCondition)tCond).getCond() );
	}
	
	private void fire( Transition t, TokensConfiguration tokens, String net) {
		for( Arc in : t.getIncoming() )
			tokens.removeToken(net, in.getPlace().getName());
		t.fire();
		for( Arc out : t.getOutgoing() ) //I know for construction that it's just one place
			tokens.addToken(net, out.getPlace().getName());
		tokens.setNetState(net, nets.getNetState(net));
	}
	
	/**
	 * The score function that elaborates the score for an ExpansionNode.
	 * If expNode has multiple destinations it sets the score to the minimum 
	 *  score obtained by its eNode destinations.   
	 *
	 * @param expNode
	 *            the expansionNode that needs a score
	 */
	private void score( ExpansionNode expNode ) {
		int score = 0;
		for( ENode destination : expNode.getDestination() ){
			score = max(score, destination.getScore());
		}
		expNode.setScore(score);
	}
	
	/**
	 * Method used to get the highest node to visit.
	 *
	 * @return the highest node to visit
	 */
	private ENode getHighestNodeToVisit(){
		
		if(toVisit.size() == 0)	return null;
		
		int index = toVisit.size() - 1;
		return toVisit.remove(index);
	}
	
	public boolean toVisitIsEmpty() {
		return toVisit.isEmpty();
	}
	
	/**
	 * Removes the expanded list.
	 */
	public void removeExpandedList(){
		this.expandedList.removeAll(this.expandedList);
	}
	
	/**
	 * This operation is used to set new Capabilities
	 *
	 * @param capabilities
	 *            the new Capabilities List
	 */
	public void setCapabilities(ArrayList<AbstractCapability> capabilities){
		this.capabilities = capabilities;
	}
	
	/**
	 * This operation is used to add a new Capability
	 *
	 * @param capability
	 *            the new Capability
	 */
	public void addCapability(AbstractCapability capability){
		this.capabilities.add(capability);
	}
	
	/**
	 * A standard method for finding the minimum value between two.
	 *
	 * @param a
	 *            the first value
	 * @param b
	 *            the second value
	 * @return the minimum between the two values
	 */
	private int max( int a, int b ){
		if( a >= b ) 
			return a;
		else 
			return b;
	}

	/** 
	 * For Testing 
	 * */
	public ArrayList<ExpansionNode> getExpandedList(){
		return this.expandedList;
	}
	
	public ArrayList<ENode> getToVisit(){
		return this.toVisit;
	}
	
	
}
